# Generated by Django 5.0.12 on 2026-02-28 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('speakers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('day', models.PositiveIntegerField(default=1, help_text='Day number within the event (1-based)')),
                ('session_type', models.CharField(blank=True, help_text='e.g. Keynote, Workshop, Break, Panel', max_length=50)),
                ('location', models.CharField(blank=True, help_text='Room or stage name', max_length=255)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='events.event')),
                ('speaker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_items', to='speakers.speaker')),
            ],
            options={
                'ordering': ['day', 'sort_order', 'start_time'],
                'indexes': [models.Index(fields=['event', 'day'], name='schedules_s_event_i_51eddb_idx')],
            },
        ),
    ]
