# Generated by Codex on 2026-03-19

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_payment_method"),
        ("tickets", "0002_registration_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderRegistration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(blank=True, max_length=20)),
                ("category_label", models.CharField(blank=True, max_length=100)),
                ("graduation_year", models.PositiveIntegerField(blank=True, null=True)),
                ("admission_number", models.CharField(blank=True, max_length=100)),
                ("student_email", models.EmailField(blank=True, max_length=254)),
                ("location_text", models.CharField(blank=True, max_length=255)),
                ("location_city", models.CharField(blank=True, max_length=100)),
                ("location_country", models.CharField(blank=True, max_length=100)),
                ("location_lat", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("location_lng", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("course", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="tickets.course")),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="registration", to="orders.order")),
                ("registration_category", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="registrations", to="tickets.registrationcategory")),
                ("school", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="tickets.school")),
            ],
        ),
        migrations.CreateModel(
            name="OrderAnswer",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("value", models.TextField(blank=True)),
                ("question", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="tickets.registrationquestion")),
                ("registration", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="answers", to="orders.orderregistration")),
            ],
        ),
    ]
