# Generated by Django 5.0.12 on 2026-02-28 11:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sponsor_logos/')),
                ('website', models.URLField(blank=True)),
                ('tier', models.CharField(choices=[('platinum', 'Platinum'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('partner', 'Partner')], default='bronze', max_length=20)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_sponsors', to='events.event')),
            ],
            options={
                'ordering': ['tier', 'sort_order', 'name'],
                'indexes': [models.Index(fields=['event', 'tier'], name='sponsors_sp_event_i_51140c_idx')],
            },
        ),
    ]
