# Generated by Django 5.0.12 on 2026-03-01 01:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_make_description_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.CharField(choices=[('speakers', 'Speakers'), ('mc', 'MC / Host'), ('venue', 'Venue / Tent'), ('equipment', 'Equipment Hire'), ('transport', 'Transport / Logistics'), ('marketing', 'Marketing'), ('catering', 'Catering'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='events.event')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
