# Generated by Codex on 2026-03-19

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200, unique=True)),
                ("code", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="RegistrationCategory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("category", models.CharField(choices=[("student", "Student"), ("alumni", "Alumni"), ("guest", "Guest")], max_length=20)),
                ("label", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("require_student_email", models.BooleanField(default=False)),
                ("require_admission_number", models.BooleanField(default=False)),
                ("ask_graduation_year", models.BooleanField(default=False)),
                ("ask_course", models.BooleanField(default=False)),
                ("ask_school", models.BooleanField(default=False)),
                ("ask_location", models.BooleanField(default=False)),
                ("event", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="registration_categories", to="events.event")),
            ],
            options={
                "ordering": ["sort_order", "category"],
                "unique_together": {("event", "category")},
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(blank=True, max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("school", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="courses", to="tickets.school")),
            ],
            options={
                "ordering": ["sort_order", "name"],
                "unique_together": {("school", "name")},
            },
        ),
        migrations.CreateModel(
            name="RegistrationQuestion",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=255)),
                ("field_type", models.CharField(choices=[("text", "Text"), ("number", "Number"), ("dropdown", "Dropdown"), ("email", "Email"), ("phone", "Phone"), ("date", "Date")], max_length=20)),
                ("is_required", models.BooleanField(default=False)),
                ("options", models.JSONField(blank=True, default=list)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("category", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="questions", to="tickets.registrationcategory")),
            ],
            options={
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.AddField(
            model_name="tickettype",
            name="registration_category",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="ticket_types", to="tickets.registrationcategory"),
        ),
    ]
