# Generated by Django 5.0.12 on 2026-02-28 11:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendee_name', models.CharField(max_length=300)),
                ('attendee_email', models.EmailField(max_length=254)),
                ('note', models.TextField(blank=True)),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_done', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='events.event')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='checkin', to='orders.ticket')),
            ],
            options={
                'indexes': [models.Index(fields=['event'], name='checkin_che_event_i_467a08_idx'), models.Index(fields=['ticket'], name='checkin_che_ticket__fa3612_idx')],
            },
        ),
    ]
