# Generated by Django 5.0.12 on 2026-03-13 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOptOut',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('category', models.CharField(choices=[('reminders', 'Event Reminders'), ('marketing', 'Marketing')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
                'unique_together': {('email', 'category')},
            },
        ),
        migrations.AddIndex(
            model_name='emailoptout',
            index=models.Index(fields=['email', 'category'], name='notificatio_email_8df6b3_idx'),
        ),
    ]
