# Generated by Django 5.0.12 on 2026-03-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_email_opt_out'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='emailoptout',
            new_name='notificatio_email_948de1_idx',
            old_name='notificatio_email_8df6b3_idx',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ticket_confirmed', 'Ticket Confirmed'), ('event_reminder', 'Event Reminder'), ('event_cancelled', 'Event Cancelled'), ('event_updated', 'Event Updated'), ('event_submitted', 'Event Submitted'), ('event_pending_review', 'Event Pending Review'), ('event_approved', 'Event Approved'), ('event_rejected', 'Event Rejected'), ('checkin_success', 'Check-in Successful'), ('refund_processed', 'Refund Processed'), ('organizer_message', 'Organizer Message')], max_length=50),
        ),
    ]
