# Generated by Django 5.0.12 on 2026-03-10 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_make_description_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='enable_waitlist',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='send_reminders',
            field=models.BooleanField(default=True),
        ),
    ]
