# Generated by Django 5.0.12 on 2026-03-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_enable_waitlist_event_send_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='reminders_sent',
            field=models.BooleanField(default=False),
        ),
    ]
