# Generated by Django 5.0.12 on 2026-03-24 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_review_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_date', 'start_time', '-published_at']},
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_status_abbd43_idx',
            old_name='events_status_review_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_status_aed975_idx',
            old_name='events_status_priority_idx',
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('rejected', 'Rejected'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=20),
        ),
    ]
