# Generated by Django 5.0.12 on 2026-03-25

import decimal
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_alter_payment_mpesa_checkout_request_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("succeeded", "Succeeded"),
                    ("failed", "Failed"),
                    ("chargeback", "Chargeback"),
                    ("refunded", "Refunded"),
                    ("partially_refunded", "Partially Refunded"),
                ],
                default="pending",
                max_length=30,
            ),
        ),
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(choices=[("stripe", "Stripe"), ("mpesa", "M-Pesa")], max_length=20)),
                ("provider_event_id", models.CharField(max_length=255)),
                ("event_type", models.CharField(blank=True, max_length=120)),
                ("payload", models.JSONField(default=dict)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[("received", "Received"), ("processed", "Processed"), ("failed", "Failed")],
                        default="received",
                        max_length=20,
                    ),
                ),
                ("processing_error", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "payment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="webhook_events",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["provider", "created_at"], name="payments_pa_provide_e9ef2e_idx"),
                    models.Index(fields=["event_type"], name="payments_pa_event_t_14989d_idx"),
                    models.Index(fields=["processing_status"], name="payments_pa_process_aeb65a_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "provider_event_id"),
                        name="payments_unique_provider_event",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ChargebackCase",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(default="stripe", max_length=20)),
                ("provider_case_id", models.CharField(max_length=255, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("warning_needs_response", "Warning Needs Response"),
                            ("warning_under_review", "Warning Under Review"),
                            ("warning_closed", "Warning Closed"),
                            ("needs_response", "Needs Response"),
                            ("under_review", "Under Review"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                        ],
                        default="needs_response",
                        max_length=40,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, default=decimal.Decimal("0"), max_digits=10)),
                ("currency", models.CharField(default="KES", max_length=3)),
                ("reason", models.CharField(blank=True, max_length=120)),
                ("due_by", models.DateTimeField(blank=True, null=True)),
                ("evidence_details_due_by", models.DateTimeField(blank=True, null=True)),
                ("opened_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("raw_payload", models.JSONField(default=dict)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chargebacks",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["provider", "provider_case_id"], name="payments_ch_provide_9ad298_idx"),
                    models.Index(fields=["status"], name="payments_ch_status_0bae77_idx"),
                    models.Index(fields=["created_at"], name="payments_ch_created_c791c8_idx"),
                ],
            },
        ),
    ]
